server {
    listen 8080;
    root /var/www/public;
    index index.php index.html;

    # Rutas de Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Procesar archivos PHP con PHP-FPM
    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Bloquear acceso a archivos ocultos
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
